import re
import httpx
from scanner.modules.base import BaseModule
from scanner.models import Finding


WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": {"server": "cloudflare", "cf-ray": ".*"},
        "cookies": ["__cfduid", "__cf_bm", "cf_clearance"],
        "body_patterns": ["Attention Required! | Cloudflare", "cf-browser-verification"],
    },
    "AWS WAF": {
        "headers": {"x-amzn-requestid": ".*", "x-amz-cf-id": ".*"},
        "cookies": ["awsalb", "awsalbcors"],
        "body_patterns": [],
    },
    "Akamai": {
        "headers": {"x-akamai-transformed": ".*", "akamai-grn": ".*"},
        "cookies": ["akamai_generated_"],
        "body_patterns": ["Access Denied.*akamai"],
    },
    "Imperva/Incapsula": {
        "headers": {"x-iinfo": ".*", "x-cdn": "Imperva"},
        "cookies": ["incap_ses_", "visid_incap_"],
        "body_patterns": ["Incapsula incident", "_Incapsula_Resource"],
    },
    "Sucuri": {
        "headers": {"x-sucuri-id": ".*", "server": "Sucuri"},
        "cookies": ["sucuri_cloudproxy_"],
        "body_patterns": ["Sucuri WebSite Firewall"],
    },
    "ModSecurity": {
        "headers": {"server": ".*ModSecurity.*"},
        "cookies": [],
        "body_patterns": ["ModSecurity", "This error was generated by Mod_Security"],
    },
    "F5 BIG-IP ASM": {
        "headers": {"x-wa-info": ".*"},
        "cookies": ["TS", "BIGip"],
        "body_patterns": ["The requested URL was rejected"],
    },
    "Barracuda": {
        "headers": {},
        "cookies": ["barra_counter_session"],
        "body_patterns": ["Barracuda Web Application Firewall"],
    },
    "Fortinet FortiWeb": {
        "headers": {},
        "cookies": ["FORTIWAFSID"],
        "body_patterns": ["FortiWeb", ".fgd_icon"],
    },
    "DDoS-Guard": {
        "headers": {"server": "ddos-guard"},
        "cookies": ["__ddg1_", "__ddg2_"],
        "body_patterns": [],
    },
    "Wordfence": {
        "headers": {},
        "cookies": ["wfwaf-authcookie"],
        "body_patterns": ["This response was generated by Wordfence"],
    },
    "Nginx (rate limiting)": {
        "headers": {"server": "nginx"},
        "cookies": [],
        "body_patterns": [],
    },
}

SECURITY_TECH_HEADERS = {
    "x-powered-by": "Server Technology",
    "server": "Server Software",
    "x-aspnet-version": "ASP.NET Version",
    "x-generator": "Site Generator",
    "x-drupal-cache": "Drupal CMS",
    "x-varnish": "Varnish Cache",
    "x-cache": "CDN/Cache Layer",
    "x-cdn": "CDN Provider",
    "via": "Proxy/CDN",
    "x-frame-options": "Clickjacking Protection",
    "content-security-policy": "CSP Policy",
    "strict-transport-security": "HSTS",
    "x-xss-protection": "XSS Protection",
    "x-content-type-options": "MIME Sniffing Protection",
    "referrer-policy": "Referrer Policy",
    "permissions-policy": "Permissions Policy",
    "feature-policy": "Feature Policy",
}


class WAFDetectorModule(BaseModule):
    name = "waf_detector"
    phase = "surface"
    description = "Detect WAF, CDN, and security infrastructure protecting the target"

    async def execute(self, job) -> list:
        findings = []
        detected_wafs = []
        security_stack = {}
        requests_count = 0
        waf_blocks = 0
        probe_paths = []

        self.log("Probing target for WAF and security infrastructure signatures...")

        try:
            async with httpx.AsyncClient(
                timeout=15, follow_redirects=True, verify=False
            ) as client:
                resp = await client.get(job.base_url)
                requests_count += 1
                headers_lower = {k.lower(): v.lower() for k, v in resp.headers.items()}
                cookies = {c.name: c.value for c in resp.cookies.jar}
                body = resp.text[:50000]

                for waf_name, sigs in WAF_SIGNATURES.items():
                    matched = False

                    for hdr_name, hdr_pattern in sigs.get("headers", {}).items():
                        if hdr_name in headers_lower:
                            if re.search(hdr_pattern, headers_lower[hdr_name], re.IGNORECASE):
                                matched = True
                                break

                    if not matched:
                        for cookie_pattern in sigs.get("cookies", []):
                            for cookie_name in cookies:
                                if cookie_pattern.lower() in cookie_name.lower():
                                    matched = True
                                    break
                            if matched:
                                break

                    if not matched:
                        for body_pattern in sigs.get("body_patterns", []):
                            if re.search(body_pattern, body, re.IGNORECASE):
                                matched = True
                                break

                    if matched:
                        detected_wafs.append(waf_name)
                        self.log(f"WAF detected: {waf_name}", "warn")

                for hdr_name, label in SECURITY_TECH_HEADERS.items():
                    if hdr_name in headers_lower:
                        security_stack[label] = headers_lower[hdr_name]

                self.log(f"Sending WAF probe requests (malicious-looking payloads)...")
                probe_paths = [
                    "/?id=1' OR '1'='1",
                    "/?q=<script>alert(1)</script>",
                    "/?file=../../../../etc/passwd",
                    "/?cmd=;cat /etc/passwd",
                    "/wp-admin/",
                    "/.env",
                    "/?debug=true",
                ]

                waf_blocks = 0
                for path in probe_paths:
                    try:
                        probe_url = job.base_url.rstrip("/") + path
                        probe_resp = await client.get(probe_url)
                        requests_count += 1
                        if probe_resp.status_code in (403, 406, 429, 503):
                            waf_blocks += 1
                            self.log(f"WAF blocked probe: {path} → HTTP {probe_resp.status_code}")
                        elif probe_resp.status_code == 200:
                            probe_headers = {k.lower(): v for k, v in probe_resp.headers.items()}
                            for waf_name, sigs in WAF_SIGNATURES.items():
                                if waf_name in detected_wafs:
                                    continue
                                for hdr_name, hdr_pattern in sigs.get("headers", {}).items():
                                    if hdr_name in probe_headers and re.search(
                                        hdr_pattern, probe_headers[hdr_name], re.IGNORECASE
                                    ):
                                        detected_wafs.append(waf_name)
                                        self.log(f"WAF detected via probe: {waf_name}", "warn")
                    except Exception:
                        pass

                self.telemetry(requestsAnalyzed=requests_count)

        except Exception as e:
            self.log(f"WAF detection error: {str(e)}", "error")

        if detected_wafs:
            waf_list = ", ".join(detected_wafs)
            f = Finding(
                severity="info",
                title=f"WAF/Security Infrastructure Detected",
                description=f"The following WAF/security systems were identified: {waf_list}. "
                f"WAF blocks on probes: {waf_blocks}/{len(probe_paths)}",
                phase=self.phase,
                recommendation="WAF presence is a positive security measure. Ensure WAF rules are comprehensive and up to date.",
                cvss_score=0.0,
            )
            findings.append(f)
            self.finding(f.severity, f.title, f.description, f.recommendation, f.cvss_score)
        else:
            f = Finding(
                severity="medium",
                title="No WAF Detected",
                description="No Web Application Firewall was detected protecting this application. "
                f"WAF blocks on probes: {waf_blocks}/{len(probe_paths)}. "
                "The application may be directly exposed to web attacks.",
                phase=self.phase,
                recommendation="Consider implementing a WAF (e.g., Cloudflare, AWS WAF, ModSecurity) to add a layer of defense.",
                cvss_score=4.0,
            )
            findings.append(f)
            self.finding(f.severity, f.title, f.description, f.recommendation, f.cvss_score)

        if security_stack:
            stack_info = "; ".join([f"{k}: {v}" for k, v in security_stack.items()])
            self.log(f"Security stack identified: {stack_info}")

            exposed_tech = []
            for label in ["Server Technology", "Server Software", "ASP.NET Version", "Site Generator"]:
                if label in security_stack:
                    exposed_tech.append(f"{label}: {security_stack[label]}")

            if exposed_tech:
                f = Finding(
                    severity="low",
                    title="Server Technology Fingerprint Exposed",
                    description=f"Server is exposing technology details: {'; '.join(exposed_tech)}. "
                    "This information helps attackers target version-specific vulnerabilities.",
                    phase=self.phase,
                    recommendation="Remove or obfuscate server version headers (X-Powered-By, Server, etc.).",
                    cvss_score=2.0,
                )
                findings.append(f)
                self.finding(f.severity, f.title, f.description, f.recommendation, f.cvss_score)

        self.log(f"WAF detection complete — {len(detected_wafs)} WAF(s) found, {len(security_stack)} security headers catalogued")
        return findings
